import "./../styles/globals.css";  
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";

export const metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="container">
          <div className="sidebar">
            <Sidebar />
          </div>
          <div className="content">{children}</div>
        </div>
      </body>
    </html>
  );
}
